# Generated by Django 4.0.3 on 2022-11-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do álbum')),
                ('data_lancamento', models.DateField(verbose_name='Data do lançamento')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('foto', models.ImageField(upload_to='album/fotos', verbose_name='Foto da capa')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da música')),
                ('audio', models.FileField(upload_to='album/audios', verbose_name='Áudio')),
                ('letra', models.TextField(verbose_name='Letra')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='album.album')),
            ],
        ),
    ]
