# Generated by Django 4.0.3 on 2022-11-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cor_fundo',
            field=models.CharField(default='#000000', max_length=100, verbose_name='Cor de fundo'),
        ),
        migrations.AddField(
            model_name='album',
            name='cor_texto',
            field=models.CharField(default='#FFFFFF', max_length=100, verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='album.album', verbose_name='Álbum'),
        ),
    ]
