# Generated by Django 4.0.3 on 2022-11-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_cor_fundo_album_cor_texto_alter_musica_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cor_fundo',
            field=models.TextField(default='#000000', verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cor_texto',
            field=models.CharField(default='#FFFFFF', max_length=100, verbose_name='Cor do texto'),
        ),
    ]
